### ISSUE TITLE
Migrations break unban timeline

### ISSUE THREAD

**Issue by omerxx** [omerxx/fatbot#52]
Migrations alter user.updated_at which breaks the time gap of 48 hours. Every deployment / process restart updates the object and resets the frame.

1. Remove migrations
2. base 48 hours on the ban event!!

**Comment by Ofirham** [comment]
joining after banned is not working.


![IMAGE 2023-05-21 21:41:49](https://github.com/omerxx/fatbot/assets/134200395/95a52013-6e14-417f-a7c5-65fbcbcc24ba)

**Comment by Ofirham** [comment]
When a member is rejoining the group, 2 exercises are being written for him - it should be corrected to 0.

*Suggestion: when someone is rejoining, the bot will answer "nice work you are ready to go now" (after sending 2 pictures) to give a feedback that it accepted  both of the pictures (instead of the regular 'nice work for the exercise' feedback)
